name: mobile_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# More about version control for real builds (prod, internal)
# you can check at ./application/fastlane/Fastfile
version: 1.0.0+1

environment:
  sdk: '^3.5.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  another_flushbar: ^1.12.30
  audio_session: ^0.1.16
  auto_route: ^5.0.4
  blur: ^3.1.0
  cached_network_image: ^3.2.3
  confetti: ^0.7.0
  connectivity_plus: ^4.0.2
  dartz: ^0.10.1
  dio: ^5.3.2
  dto:
    git:
      url: https://github.com/kazky-dytynstva/dto
      ref: 1.0.7
  equatable: ^2.0.5
  firebase_analytics: ^10.4.5
  firebase_app_installations: ^0.2.3+5
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_database: ^10.2.5
  firebase_remote_config: ^4.2.5
  flip_board: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_email_sender: ^6.0.1
  flutter_link_previewer: ^3.2.2
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  hive: ^2.2.3
  in_app_review: ^2.0.6
  injectable: ^2.3.0
  json_annotation: ^4.8.1
  just_audio: ^0.9.34
  just_audio_background: 0.0.1-beta.10
  meta: ^1.9.1
  open_store: ^0.5.0
  package_info_plus: ^4.1.0
  page_indicator: ^0.4.1
  path_provider: ^2.1.0
  scroll_to_index: ^3.0.1
  share_plus: ^7.1.0
  sprintf: ^7.0.0
  stream_transform: ^2.1.0
  super_rich_text: ^1.0.0
#  transformer_page_view: 0.1.6
  update_available: ^3.0.0
  url_launcher: ^6.1.12
  visibility_detector: ^0.4.0+2
  watcher: 1.1.0

dev_dependencies:
  auto_route_generator: ^5.0.3
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.0

flutter_icons:
  image_path_android: "assets/launcher/android.png"
  image_path_ios: "assets/launcher/ios.png"
  android: true                                                         # can specify file name here e.g. "ic_launcher"
  ios: true                                                             # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/launcher/android_background.png"    # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/launcher/android_foreground.png"    # only available for Android 8.0 devices and above


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/launcher/
    - assets/icons/
    - assets/graphics/

  fonts:
    - family: Kotyhoroshko
      fonts:
        - asset: assets/fonts/Kotyhoroshko-Bold.otf
